2025-08-26 09:45:00.603 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration display_tools which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-08-26 09:45:01.535 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2025-08-26 09:45:04.825 WARNING (MainThread) [homeassistant.config_entries] Config entry 'gydota@gmail.com' for tuya integration could not authenticate: Authentication failed. Please re-authenticate
2025-08-26 09:45:05.500 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/__init__.py:2: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  __import__('pkg_resources').declare_namespace(__name__)

2025-08-26 09:45:06.487 ERROR (MainThread) [homeassistant.components.esphome.manager] Unexpected device found at 192.168.88.16; expected `dallas-shower` with mac address `3c:84:27:c7:11:bc`, found `ld-2410` with mac address `a0:b7:65:6b:0a:4c`
2025-08-26 09:45:06.571 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.display_02_sram_usage (<class 'homeassistant.components.esphome.sensor.EsphomeSensor'>) is using native unit of measurement 'KB' which is not a valid unit for the device class ('data_size') it is using; expected one of ['ZB', 'EB', 'MiB', 'TB', 'ZiB', 'GB', 'GiB', 'MB', 'Gbit', 'PiB', 'bit', 'kB', 'Mbit', 'TiB', 'KiB', 'B', 'YiB', 'EiB', 'PB', 'YB', 'kbit']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+esphome%22
2025-08-26 09:45:09.356 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for esphome-web-4c8830 @ 192.168.88.39: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='192.168.88.39', port=6053))]: [Errno 113] Connect call failed ('192.168.88.39', 6053) (SocketAPIError)
2025-08-26 09:45:09.356 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for perenoska_bedroom @ 192.168.88.101: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='192.168.88.101', port=6053))]: [Errno 113] Connect call failed ('192.168.88.101', 6053) (SocketAPIError)
2025-08-26 09:45:09.357 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 4-sockets-black @ 192.168.88.105: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='192.168.88.105', port=6053))]: [Errno 113] Connect call failed ('192.168.88.105', 6053) (SocketAPIError)
2025-08-26 09:45:09.357 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for kotel @ 192.168.88.103: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='192.168.88.103', port=6053))]: [Errno 113] Connect call failed ('192.168.88.103', 6053) (SocketAPIError)
2025-08-26 09:49:21.485 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 09:59:18.942 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 10:04:56.272 ERROR (MainThread) [frontend.js.modern.202508110] Uncaught error from Chrome 139.0.0.0 on Windows 10
Error: Attempting to use a disconnected port object
sendToOrigin (/extensionServiceWorker.js:47884:12)
dAppUpdater (/extensionServiceWorker.js:47877:7)
sendUpdates (/extensionServiceWorker.js:49341:5)
connectSite (/extensionServiceWorker.js:49351:3)
async onMessage (/extensionServiceWorker.js:47947:9)
2025-08-26 10:04:56.299 ERROR (MainThread) [frontend.js.modern.202508110] Uncaught error from Chrome 139.0.0.0 on Windows 10
Error: Attempting to use a disconnected port object
sendToOrigin (/extensionServiceWorker.js:47884:12)
dAppUpdater (/extensionServiceWorker.js:47877:7)
sendUpdates (/extensionServiceWorker.js:49341:5)
connectSite (/extensionServiceWorker.js:49351:3)
async onMessage (/extensionServiceWorker.js:47947:9)
2025-08-26 10:04:56.345 ERROR (MainThread) [frontend.js.modern.202508110] Uncaught error from Chrome 139.0.0.0 on Windows 10
Error: Attempting to use a disconnected port object
sendToOrigin (/extensionServiceWorker.js:47884:12)
dAppUpdater (/extensionServiceWorker.js:47877:7)
sendUpdates (/extensionServiceWorker.js:49341:5)
connectSite (/extensionServiceWorker.js:49351:3)
async onMessage (/extensionServiceWorker.js:47947:9)
2025-08-26 10:11:46.178 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 10:13:18.616 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 10:15:23.260 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 10:17:15.038 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 10:18:15.219 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 10:19:15.364 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 10:20:15.572 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 10:22:21.224 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 10:24:21.254 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 10:28:15.706 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 10:32:26.989 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 10:38:03.380 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 10:43:58.582 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 10:46:33.956 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 10:48:04.155 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 10:52:33.742 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 10:57:10.884 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 10:58:41.048 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 11:07:03.689 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 11:12:55.324 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 11:13:55.484 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 11:16:52.185 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 11:20:11.748 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 11:21:32.047 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 11:23:02.356 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 11:27:13.032 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 11:37:39.014 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 11:38:39.167 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 11:44:05.448 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 11:46:45.127 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 11:47:45.352 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 11:48:45.548 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 11:56:18.360 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 11:58:18.164 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 12:01:35.671 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][component:279]: esphome.ota set Warning flag: unspecified
2025-08-26 12:02:17.494 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 12:02:42.925 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][component:307]: esphome.ota cleared Warning flag
2025-08-26 12:02:53.054 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][component:407]: lvgl took a long time for an operation (151 ms)
2025-08-26 12:02:53.054 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][component:408]: Components should block for at most 30 ms
2025-08-26 12:03:26.721 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][component:407]: lvgl took a long time for an operation (246 ms)
2025-08-26 12:03:26.731 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][component:408]: Components should block for at most 30 ms
2025-08-26 12:03:28.227 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][lvgl:000]: draw_bg_img: Couldn't read the background image 	(in lv_draw_sw_rect.c line #391)
2025-08-26 12:03:28.434 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][component:407]: lvgl took a long time for an operation (265 ms)
2025-08-26 12:03:28.444 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][component:408]: Components should block for at most 30 ms
2025-08-26 12:03:28.494 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][lvgl:000]: draw_bg_img: Couldn't read the background image 	(in lv_draw_sw_rect.c line #391)
2025-08-26 12:03:29.557 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][lvgl:000]: draw_bg_img: Couldn't read the background image 	(in lv_draw_sw_rect.c line #391)
2025-08-26 12:03:29.752 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][lvgl:000]: draw_bg_img: Couldn't read the background image 	(in lv_draw_sw_rect.c line #391)
2025-08-26 12:03:34.819 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities script.radio_1 are missing or not currently available
2025-08-26 12:03:35.613 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities script.radio_2 are missing or not currently available
2025-08-26 12:03:51.869 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities script.radio_1 are missing or not currently available
2025-08-26 12:03:53.465 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities script.radio_1 are missing or not currently available
2025-08-26 12:03:54.156 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities script.radio_2 are missing or not currently available
2025-08-26 12:03:55.362 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][lvgl:000]: draw_bg_img: Couldn't read the background image 	(in lv_draw_sw_rect.c line #391)
2025-08-26 12:03:55.523 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][lvgl:000]: draw_bg_img: Couldn't read the background image 	(in lv_draw_sw_rect.c line #391)
2025-08-26 12:03:58.689 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][lvgl:000]: draw_bg_img: Couldn't read the background image 	(in lv_draw_sw_rect.c line #391)
2025-08-26 12:03:58.825 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][lvgl:000]: draw_bg_img: Couldn't read the background image 	(in lv_draw_sw_rect.c line #391)
2025-08-26 12:03:59.008 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][lvgl:000]: draw_bg_img: Couldn't read the background image 	(in lv_draw_sw_rect.c line #391)
2025-08-26 12:05:02.631 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities script.radio_2 are missing or not currently available
2025-08-26 12:10:49.539 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][api.connection:142]: ESPHome Logs 2025.7.5 (192.168.88.33): Connection closed
2025-08-26 12:11:07.512 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities script.radio_3 are missing or not currently available
2025-08-26 12:13:30.235 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][lvgl:000]: draw_bg_img: Couldn't read the background image 	(in lv_draw_sw_rect.c line #391)
2025-08-26 12:13:30.395 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][lvgl:000]: draw_bg_img: Couldn't read the background image 	(in lv_draw_sw_rect.c line #391)
2025-08-26 12:14:37.550 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 100, in wrapper
    return_value = func(self, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 542, in turn_off
    self._get_chromecast().quit_app()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/pychromecast/__init__.py", line 463, in quit_app
    response_handler.wait_response()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/pychromecast/response_handler.py", line 54, in wait_response
    raise RequestTimeout(self._request, self._timeout)
pychromecast.error.RequestTimeout: Execution of quit app timed out after 10.0 s.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2835, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2878, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 850, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 922, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 831, in async_turn_off
    await self.hass.async_add_executor_job(self.turn_off)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 102, in wrapper
    raise HomeAssistantError(
        f"{self.__class__.__name__}.{func.__name__} Failed: {err}"
    ) from err
homeassistant.exceptions.HomeAssistantError: CastMediaPlayerEntity.turn_off Failed: Execution of quit app timed out after 10.0 s.
2025-08-26 12:14:38.014 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][lvgl:000]: draw_bg_img: Couldn't read the background image 	(in lv_draw_sw_rect.c line #391)
2025-08-26 12:14:38.146 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][lvgl:000]: draw_bg_img: Couldn't read the background image 	(in lv_draw_sw_rect.c line #391)
2025-08-26 12:14:38.340 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][lvgl:000]: draw_bg_img: Couldn't read the background image 	(in lv_draw_sw_rect.c line #391)
2025-08-26 12:14:40.031 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities script.radio_3 are missing or not currently available
2025-08-26 12:14:57.073 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][lvgl:000]: draw_bg_img: Couldn't read the background image 	(in lv_draw_sw_rect.c line #391)
2025-08-26 12:14:57.225 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][lvgl:000]: draw_bg_img: Couldn't read the background image 	(in lv_draw_sw_rect.c line #391)
2025-08-26 12:15:08.136 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 12:18:57.738 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 12:21:38.480 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 12:23:19.952 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 12:25:09.942 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 12:26:51.567 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 12:30:33.232 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 12:32:20.886 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 12:38:38.503 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 12:42:39.066 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 12:46:13.939 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 12:47:14.072 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 12:49:16.614 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 12:50:16.782 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 12:51:16.998 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 12:52:17.139 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 12:53:17.292 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 12:55:17.028 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 12:57:16.874 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 12:59:58.126 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 13:01:17.960 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 13:03:20.428 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 13:05:01.949 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 13:06:44.059 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 13:06:46.459 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][component:279]: esphome.ota set Warning flag: unspecified
2025-08-26 13:07:51.496 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][component:307]: esphome.ota cleared Warning flag
2025-08-26 13:07:58.713 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for display-02 @ 192.168.88.48: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='192.168.88.48', port=6053))]: [Errno 111] Connect call failed ('192.168.88.48', 6053) (SocketAPIError)
2025-08-26 13:08:01.715 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][component:407]: lvgl took a long time for an operation (154 ms)
2025-08-26 13:08:01.724 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][component:408]: Components should block for at most 30 ms
2025-08-26 13:11:28.684 ERROR (Thread-5) [pychromecast.socket_client] [Телевізор у кухні(192.168.88.41):8009] Failed to connect to service HostServiceInfo(host='192.168.88.41', port=8009), retrying in 5.0s
2025-08-26 13:14:10.132 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][component:407]: lvgl took a long time for an operation (242 ms)
2025-08-26 13:14:10.132 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][component:408]: Components should block for at most 30 ms
2025-08-26 13:14:11.312 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][lvgl:000]: draw_bg_img: Couldn't read the background image 	(in lv_draw_sw_rect.c line #391)
2025-08-26 13:14:11.512 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][component:407]: lvgl took a long time for an operation (263 ms)
2025-08-26 13:14:11.531 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][component:408]: Components should block for at most 30 ms
2025-08-26 13:14:11.573 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][lvgl:000]: draw_bg_img: Couldn't read the background image 	(in lv_draw_sw_rect.c line #391)
2025-08-26 13:14:12.431 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][lvgl:000]: draw_bg_img: Couldn't read the background image 	(in lv_draw_sw_rect.c line #391)
2025-08-26 13:14:12.591 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][lvgl:000]: draw_bg_img: Couldn't read the background image 	(in lv_draw_sw_rect.c line #391)
2025-08-26 13:14:27.686 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities script.radio_1 are missing or not currently available
2025-08-26 13:15:10.280 WARNING (MainThread) [homeassistant.components.esphome.manager] display-02: [W][api.connection:142]: ESPHome Logs 2025.7.5 (192.168.88.33): Connection closed
